In [1]:
# Numpy -> 배열을 다루는 도구
# np.array(list) -> 리스트로 numpy 배열을 만드는 함수. 리스트가 중첩된 깊이가 곧 배열의 차원이 됨
# 1차원 배열 생성하기
import numpy as np

numpy_array = np.array([1,2,3,4])
numpy_array

array([1, 2, 3, 4])

In [2]:
# 2차원 배열 생성
numpy_array2 = np.array([[1,2,3,4,],[11,12,13,14]])
numpy_array2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [3]:
# 3차원 배열 생성
numpy_array3 = np.array([[[1,2,3,4],[11,12,13,14]], [[21,22,23,24],[31,32,33,34]]])
numpy_array3

array([[[ 1,  2,  3,  4],
        [11, 12, 13, 14]],

       [[21, 22, 23, 24],
        [31, 32, 33, 34]]])

In [5]:
# 배열의 모양보기
print(numpy_array)
print(numpy_array2)
print(numpy_array3)

[1 2 3 4]
[[ 1  2  3  4]
 [11 12 13 14]]
[[[ 1  2  3  4]
  [11 12 13 14]]

 [[21 22 23 24]
  [31 32 33 34]]]


In [9]:
# 다차원 배열 만들기
z1 = np.zeros([4]) # 0으로 채운 배열 만들기
o2 = np.ones([3,4]) # 1로 채운 배열, 4개의 요소 값을 가지는 3개의 리스트 생성
r2 = np.random.randn(2,3) # 3개의 행 2개의 열을 가지는 랜덤한 숫자 배열
print(z1)
print(o2)
print(r2)

[0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[-1.36581226 -1.74306828  1.01405703]
 [-0.57088546  0.57464178  0.1045684 ]]


In [10]:
print(z1.shape)
print(o2.shape)
print(r2.shape)

(4,)
(3, 4)
(2, 3)


In [11]:
# 4차원 이상 생성
r4 = np.random.randn(2,2,4,5).round(3)
r4

array([[[[ 0.198,  1.369,  0.826, -1.225, -0.783],
         [ 0.499,  0.299, -1.798,  0.623,  0.434],
         [-0.554, -0.599, -0.826,  1.658, -1.041],
         [ 0.56 , -0.229, -1.85 ,  1.131,  0.225]],

        [[-0.2  , -2.441,  1.574,  0.108,  0.054],
         [ 0.707, -1.589, -0.248,  0.466,  0.28 ],
         [ 0.84 , -0.141,  0.549, -0.4  ,  0.215],
         [-0.25 ,  0.461, -1.371,  0.117, -0.44 ]]],


       [[[ 0.073,  1.413,  0.78 ,  0.948, -0.278],
         [-1.277,  0.589, -0.155,  0.36 ,  0.82 ],
         [-1.489, -0.952, -1.341, -1.209, -1.054],
         [ 0.059,  0.493, -0.864, -0.049, -0.044]],

        [[-0.944,  1.69 , -0.531, -0.749, -0.505],
         [ 1.111,  1.937, -0.176,  0.305, -1.027],
         [-0.337, -0.901, -0.8  ,  1.476,  1.26 ],
         [ 1.877,  1.053, -0.505,  0.459, -0.237]]]])

In [16]:
# Indexing
index = r4[1][0] # 두번째 배열에서 첫번째 배열 접근해서 가져오기
index2 = r4[1][0][2] # 두번째 배열의 첫번째 배열의 두번째 배열 가져오기
index3 = r4[1,0,2] # 이렇게도 표현가능
print(index, index2, index3)

[[ 0.073  1.413  0.78   0.948 -0.278]
 [-1.277  0.589 -0.155  0.36   0.82 ]
 [-1.489 -0.952 -1.341 -1.209 -1.054]
 [ 0.059  0.493 -0.864 -0.049 -0.044]] [-1.489 -0.952 -1.341 -1.209 -1.054] [-1.489 -0.952 -1.341 -1.209 -1.054]


In [17]:
# Slicing
r4[1][0][2][0:4:2] # 가져오는 마지막 원소가 끝을 포함하지 않음

array([-1.489, -1.341])

In [29]:
# numpy간 사칙연산
arr = np.array([[1,2,3,4],[10,11,12,13]])
arr

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [21]:
# Broadcasting 연산 (Scalar)
# numpy배열의 모든 원소에 해당 숫자 사칙 연산이 확장되어 적용
S1 = arr + 20 # 덧셈 브로드캐스팅
S2 = arr * 100 # 곱셈 브로드캐스팅
print(S1,S2)

[[21 22 23 24]
 [30 31 32 33]] [[ 100  200  300  400]
 [1000 1100 1200 1300]]


In [25]:
# Aggregation
A1 = arr.sum() # (모든 원소에 대해)합계
A2 = arr.mean() # 평균
A3 = arr.prod() # 곱셈
A4 = arr.max() # 최댓값
A5 = arr.min() # 최솟값
print(A1,A2,A3,A4,A5)

56 7.0 411840 13 1


In [30]:
# 배열에서의 최대인 원소의 번호, 최소인 원소의 번호
arr.argmax(), arr[1].argmax(), arr.argmin()

(7, 3, 0)

In [31]:
# indexing + Slicing + Aggregation 응용
arr[1].min(), arr[1][2].sum()

(10, 12)

In [34]:
# 특정 축(차원)으로 덧셈 수행하기
arr.sum(axis=0), arr.sum(axis=1)

(array([11, 13, 15, 17]), array([10, 46]))

In [42]:
# Pandas
import pandas as pd
path = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/module_5_auto.csv'
df = pd.read_csv(path)

In [46]:
df.index

RangeIndex(start=0, stop=201, step=1)

In [52]:
df.loc[0] # 인덱스로 접근

Unnamed: 0.1                   0
Unnamed: 0                     0
symboling                      3
normalized-losses            122
make                 alfa-romero
aspiration                   std
num-of-doors                 two
body-style           convertible
drive-wheels                 rwd
engine-location            front
wheel-base                  88.6
length                  0.811148
width                   0.890278
height                      48.8
curb-weight                 2548
engine-type                 dohc
num-of-cylinders            four
engine-size                  130
fuel-system                 mpfi
bore                        3.47
stroke                      2.68
compression-ratio            9.0
horsepower                 111.0
peak-rpm                  5000.0
city-mpg                      21
highway-mpg                   27
price                    13495.0
city-L/100km           11.190476
horsepower-binned         Medium
diesel                         0
gas       

In [53]:
df.iloc[0] # 배열 번호로 접근

Unnamed: 0.1                   0
Unnamed: 0                     0
symboling                      3
normalized-losses            122
make                 alfa-romero
aspiration                   std
num-of-doors                 two
body-style           convertible
drive-wheels                 rwd
engine-location            front
wheel-base                  88.6
length                  0.811148
width                   0.890278
height                      48.8
curb-weight                 2548
engine-type                 dohc
num-of-cylinders            four
engine-size                  130
fuel-system                 mpfi
bore                        3.47
stroke                      2.68
compression-ratio            9.0
horsepower                 111.0
peak-rpm                  5000.0
city-mpg                      21
highway-mpg                   27
price                    13495.0
city-L/100km           11.190476
horsepower-binned         Medium
diesel                         0
gas       

In [56]:
df.loc[0:2]

Unnamed: 0.1  Unnamed: 0  symboling  normalized-losses         make  \
0             0           0          3                122  alfa-romero   
1             1           1          3                122  alfa-romero   
2             2           2          1                122  alfa-romero   

  aspiration num-of-doors   body-style drive-wheels engine-location  ...  \
0        std          two  convertible          rwd           front  ...   
1        std          two  convertible          rwd           front  ...   
2        std          two    hatchback          rwd           front  ...   

   compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg    price  \
0                9.0       111.0    5000.0        21           27  13495.0   
1                9.0       111.0    5000.0        21           27  16500.0   
2                9.0       154.0    5000.0        19           26  16500.0   

  city-L/100km  horsepower-binned diesel  gas  
0    11.190476             Medium      0    1  
1    11.190476             Medium      0    1  
2    12.368421             Medium      0    1  

[3 rows x 31 columns]

In [57]:
df.iloc[0:2] # 끝 포함 안함

Unnamed: 0.1  Unnamed: 0  symboling  normalized-losses         make  \
0             0           0          3                122  alfa-romero   
1             1           1          3                122  alfa-romero   

  aspiration num-of-doors   body-style drive-wheels engine-location  ...  \
0        std          two  convertible          rwd           front  ...   
1        std          two  convertible          rwd           front  ...   

   compression-ratio  horsepower  peak-rpm  city-mpg  highway-mpg    price  \
0                9.0       111.0    5000.0        21           27  13495.0   
1                9.0       111.0    5000.0        21           27  16500.0   

  city-L/100km  horsepower-binned diesel  gas  
0    11.190476             Medium      0    1  
1    11.190476             Medium      0    1  

[2 rows x 31 columns]

In [64]:
df.dtypes

Unnamed: 0.1           int64
Unnamed: 0             int64
symboling              int64
normalized-losses      int64
make                  object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                 float64
stroke               float64
compression-ratio    float64
horsepower           float64
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                float64
city-L/100km         float64
horsepower-binned     object
diesel                 int64
gas                    int64
dtype: object

In [65]:
# ::으로 모든 원소 지칭
df.loc[::, 'symboling']

0      3
1      3
2      1
3      2
4      2
      ..
196   -1
197   -1
198   -1
199   -1
200   -1
Name: symboling, Length: 201, dtype: int64

In [66]:
# : 한번만 사용 가능
df.iloc[5, :]

Unnamed: 0.1                 5
Unnamed: 0                   5
symboling                    2
normalized-losses          122
make                      audi
aspiration                 std
num-of-doors               two
body-style               sedan
drive-wheels               fwd
engine-location          front
wheel-base                99.8
length                0.851994
width                 0.920833
height                    53.1
curb-weight               2507
engine-type                ohc
num-of-cylinders          five
engine-size                136
fuel-system               mpfi
bore                      3.19
stroke                     3.4
compression-ratio          8.5
horsepower               110.0
peak-rpm                5500.0
city-mpg                    19
highway-mpg                 25
price                  15250.0
city-L/100km         12.368421
horsepower-binned       Medium
diesel                       0
gas                          1
Name: 5, dtype: object

In [67]:
df.iloc[0, :].shape

(31,)