In [5]:
import numpy as np

a = np.arange(0, 10, step=5) # step=간격. 0~9사이의 값을 간격만큼 띄워 배열로 전환. end값은 포함되지 않을 수 있음
b = np.arange(1, 10, step=5)
c = np.arange(0, 10, step=1)

print(a, b, c, sep='\n')

[0 5]
[1 6]
[0 1 2 3 4 5 6 7 8 9]


In [7]:
# num=개수, endpoit가 True일 경우 end의 값이 마지막 값. False일 경우 end의 값을 end의 값을 마지막 값으로 사용하지 않음
# retstep이 True일 경우 값들의 간격을 배열에 포함함
a = np.linspace(0, 10, num=5, endpoint=True, retstep=True)
b = np.linspace(1, 10, num=5, endpoint=True, retstep=False)
c = np.linspace(0, 10, num=5, endpoint=False, retstep=False)

print(a, b, c, sep='\n')

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), 2.5)
[ 1.    3.25  5.5   7.75 10.  ]
[0. 2. 4. 6. 8.]
